### ISSUE TITLE
Config file for the action

### ISSUE THREAD

**Issue by alambike** [prefapp/action-make-state-repos-dispatches#2]
### Motivation
We want to define the structure of the action config file, that the user must have created in its repository.

Default config file path: `.github/make_dispatches.yml`

```yaml
dispatches:
   # APIS
  - type: snapshots # MANDATORY
    flavors: # MANDATORY
      - default
    state_repos: # MANDATORY
      - repo: my-state-1 # (mandatory)
        base_path: apps # (optional)
        tenant: mytenant1 # (mandatory)
        application: my-app # (mandatory)
        env: dev # (mandatory)
        service_names: ['controller'] # (mandatory)
        registry: my_registry_address # (OPTIONAL: uses org SNAPSHOTS vs RELEASES)
        version: branch_dev | latest_release | latest_prerelease | release tag | commit-sha # (mandatory)
        
      - repo: my-state-repo2
        registry: my_registry_address 
        tenant: mytenant2
        application: my-app2
        env: pre
        service_names: ['controller']
        version: branch_dev | latest_release | latest_prerelease | release tag | commit-sha # (mandatory)

  # frontends
  - type: releases
    flavors:
      - flavor1
    state_repos:
      - repo: my_state_repo1
        base_path: apps
        tenant: mytenant1
        application: myapp1
        env: dev
        service_names: ['controller']
        version: branch_dev | latest_release | latest_prerelease | release tag | commit-sha # (mandatory)

  - type: releases
    flavors: 
      - flavor2
    state_repos:
      - repo: my_state2
        tenant: 
        application: myapp1
        env: pre
        service_names: ['controller']
        version: branch_dev | latest_release | latest_prerelease | release tag | commit-sha # (mandatory)
 ```
