### ISSUE TITLE
Load dispatches file locally first

### ISSUE THREAD

**Issue by alambike** [prefapp/action-make-state-repos-dispatches#20]
### Motivation
As we use the action after a checkout

```yaml
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

...
      - name: Dispatch image changes to state repos
        uses: prefapp/action-make-state-repos-dispatches@v1
        env:
          DEBUG: '*'

```

The dispatches file must be loaded locally, instead of bring it from the GitHub API, to use the version from the current checkout, related to the triggered event, instead of the version from the repo default branch

https://github.com/prefapp/action-make-state-repos-dispatches/blob/4c754fc7458efd19e0c9e1699ba918cef239c7ca/src/main.js#L76-L94

If the file is not located locally, we can use the GitHub API as a fallback, but first we need to check it locally.

And I would refactor the code to use a function, and would add some testing to be able to do this kind of changes with more peace of mind.
