### ISSUE TITLE
Config v2: Refactor config file to improve end-user usability

### ISSUE THREAD

**Issue by alambike** [prefapp/action-make-state-repos-dispatches#21]
### Motivation

To improve usability for the end user, we want to refactor the `make-dispatches.yml` file, to more clearly indicate the purpose of each dispatch, mixing what the development team can define in `make_dispatches.yml`, with what the platform team knows (what application, and state-repo, the code repository belongs, what's the name of the services the repository provides).

## code repo
```yaml
---
# SPA clients
deployments:
  - tenant: tenant1
    platform: eu-aks-1
    env: dev
    type: snapshots
    flavor: tenant1-dev
    version: $branch_dev

  - tenant: tenant1
    platform: eu-aks-1
    env: pro
    type: releases
    flavor: tenant1-pro
    version: $latest_prerelease
```
```yaml
---
# apis
deployments:
  -  tenant: tenant2
     platform: eu-aks-1
     type: snapshots
     flavor: default
     env: dev
     version: $branch_dev
     application: app1
     service_names: ["my-client-app1"] # opcional, subconjunto de los services names definidos en .firestarter/applications/app1.yml
     registry: xxx  # opcional, para indicar otro registry diferente al default donde está alojada la imagen
     image_repository: aaa/bbb # opcional, necesario para indicar el repositorio de la imagen, dentro del custom registry, es decir, cuando se está usando un registry diferente al por defecto de la organización
        
  -  tenant: tenant3
     platform: eu-aks-1
     env: dev
     version: $branch_dev
     type: snapshots
     flavor: default
     service_names: ["my-client-app2", "manolito"] # opcional, subconjunto de los services names definidos en .firestarter/applications/app1.yml
     application: app2
        
  -  tenant: tenant4
     platform: eu-aks-1
     env: pre
     type: snapshots
     flavor: default
     version: $latest_prerelease
```

### Applications
**This definition will be located in the default branch of the `.firestartr` repository**
**.firestart/apps/xxx.yml**

```yaml
  # my-app1.yml
  name: my-app1
  state_repo: "org/state-app-app1"
  services:
    - repo: org/my-app1-client
      service_names: [app-client]
    - repo: org/my-app1-api
      service_names: [app-api]
```
```yaml
  # my-app2.yml
  name: my-app2
  state_repo: "org/state-app-app2"
  services:
    - repo: org/my-app2-api
      service_names: ["my-app2"]
```
```yaml
  # my-app3.yml
  name: my-app3
  state_repo: "org/my-app3" # <- application with only 1 service, state_repo can be in the same repo
  services:
    - repo: org/my-app3
      service_names:
        - app3-api
        - app3-api-consumer
        - app3-api-webhook
        - app3-worker
```

### platforms
**.firestart/platforms/xxx.yml**
```yaml
type: aks-cluster
name: myclusteraks1
tenants: [tenant1, tenant2, tenant3]
envs: [dev, pre]
```
```yaml
type: vmss
name: myvmss1
tenants: [tenant1, tenant2, tenant3]
envs: [dev, pre]
```

### docker registries
**.firestart/docker_registries/yyy.yml**

```yaml
name: myreleasesacr
registry: acrreleases.azurecr.io
default: true
image_types: [releases]
base_paths:
  services: "projects"
  charts: "charts"
```

**.firestart/docker_registries/zzz.yml**
```yaml
name: mysnapshotsacr
registry: acrsnapshots.azurecr.io
image_type: [snapshots]
default: true
auth_strategy: aws_oidc | azure_oidc | generic | ghcr | dockerhub
base_paths:
  services: "projects"
  charts: "charts"
```

```yaml
# registry for docker images of services 
name: dockerhub
registry: hub.docker.io
default: true
auth_strategy: aws_oidc | azure_oidc | generic | ghcr | dockerhub
image_types: [releases, snapshost]
base_paths:
  services: "<myorg>"
```
```yaml
# registry for docker images of charts
name: myawsecr
auth_strategy: aws_oidc | azure_oidc | generic | ghcr | dockerhub
registry: myecr.awsxcvcs.com
image_types: [releases, snapshost]
base_paths:
  charts: ""
```

### Conditions
Per every deployment we need to check:
1. Find the corresponding application in the apps folder (using the `name` attribute)
2. Checks:
    - services_names match the allowed list of services_names, for that service repo?
    - tenant is allowed in the specified cluster?
    - env is allowed in the specified cluster?
3. Dispatch with `dispatch_event_type` equal to `dispatch-image-[platform.type]`
