### ISSUE TITLE
Changes to the workflow

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/action-make-state-repos-dispatches#4]
# Motivation
We need to define the following new requisites for our workflow:

- A new repository variable, `DOCKER_REGISTRIES_BASE_PATHS`, will be created. It will be used to create the full URL of the image repository we want to dispatch or where we want to upload the freshly built image. It will be constructed as follows: `var.DOCKER_REGISTRY_[RELEASES or SNAPSHOTS]`/`DOCKER_REGISTRIES_BASE_PATHS[services][releases or snapshots]`/`github.repository`. It will be used only when dealing with the default image repository name (that is, the Github repo name) and only for one of the default docker registries. The data contained in the variable will be in YAML format, like this: 

```yaml
services:
  releases: <path>
  snapshots: <path>
charts:
  releases: <path>
  snapshots: <path>
runners:
  releases: <path>
  snapshots: <path>
```

- When automatically calling this workflow, always build ALL flavors for ALL state repos for a given dispatch type

### Acceptance criteria
- [ ] The new variable has been implemented into the workflow
- [ ] "*" is received as an input for flavors and state repos when workflow is automatically called
- [ ] Team acceptance
