### ISSUE TITLE
Support platform and claim keys on `make_dispatches.yaml` interface

### ISSUE THREAD

**Issue by tonirvega** [prefapp/action-make-state-repos-dispatches#93]
# Motivation

In order to support claims dispatches, we need to add a new key in the dispatches user managed file called `make_dispatches.yaml`.

```yaml
deployments:
  - tenant: <tenant>
    platform: azure-<tenant> 
    # The platform is determined by the reference to the subscription type and an identifier that may be related to the tenant.
    # Examples:
    # If we have a tenant that contains all environments:
    #  platform: mongo-atlas-corpme
    #  platform: azure-corpme

    # If we have a tenant that contains the dev and pre environments:
    #  platform: mongo-atlas-saas-predev
    #  platform: azure-saas-predev

    # If we have a tenant that contains the production environment:
    #  platform: mongo-atlas-saas-pro
    #  platform: azure-saas-pro

    claim: <claim-name> # new field
    type: snapshots
    flavor: default
    application: <app-name>
    env: <env>
    image_keys: ['run_script/docker_image']
    version: $latest_prerelease
```

# Acceptance Criteria

- [x] The dispatch can transmit the information using the new `claims` key.
- [x] Tests have been passed
- [ ] A new major version has been released.
- [ ] Team acceptance
